import { ClerkProvider } from '@clerk/nextjs'
import { Open_Sans } from 'next/font/google'

import { cn } from '@/lib/utils'

import './globals.css'
import type { Metadata } from 'next'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(font.className, 'bg-white dark:bg-[#313338]')}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
